config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  namespace :app do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    resources :job_reports do
      member do
        post :certificate
      end
    end
    resources :jobs do
      member do
        post :repeat
      end
    end
    resources :customers
    resources :users do
      collection do
        get :profile
      end
    end
  end

  namespace :admin do
    resources :users
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                      :integer          not null, primary key
#  customer                :string
#  user                    :string
#  title                   :string
#  description             :string
#  scheduled_date          :date
#  completed_date          :date
#  status                  :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  customer_id             :integer
#  user_id                 :integer
#  invoice_number          :string
#  attachment_file_name    :string
#  attachment_content_type :string
#  attachment_file_size    :integer
#  attachment_updated_at   :datetime
#

class Job < ApplicationRecord
  STATUS = [
    STATUS_COMPLETED = "Completed",
    STATUS_ALLOCATED = "Allocated"
  ]
  belongs_to :customer
  belongs_to :user, optional: true
  has_many :job_reports

  validates_presence_of :scheduled_date

  has_attached_file :attachment
  validates_attachment_content_type :attachment,
    content_type: [
      'application/pdf'
    ]
  validates_attachment_size :attachment, less_than: 10.megabytes
end

app/controllers/app/jobs_controller.rb
class App::JobsController < App::BaseController
  layout 'admin'
  before_action :set_job, only: [:show, :edit, :update, :destroy, :repeat]

  def index
    @query = Job.includes(:user, :customer).ransack(params[:q])
    @jobs = @query.result(scheduled_date: :desc)
                                     .page(params[:page])
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new user_id: current_user.id
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        if params[:type] != 'none'
          clone_job = @job
          (1..params[:repeats].to_i).each do |index|
            clone_job = clone_job.dup
            case params[:type]
              when 'weekly'
                clone_job.scheduled_date = clone_job.scheduled_date.to_date + 1.week
                clone_job.completed_date = clone_job.completed_date.to_date + 1.week if clone_job.completed_date.try(:to_date)

              when 'monthly'
                clone_job.scheduled_date = clone_job.scheduled_date.to_date + 1.month
                clone_job.completed_date = clone_job.completed_date.to_date + 1.month if clone_job.completed_date.try(:to_date)

              when 'quarterly'
                clone_job.scheduled_date = clone_job.scheduled_date.to_date + 3.month
                clone_job.completed_date = clone_job.completed_date.to_date + 3.month if clone_job.completed_date.try(:to_date)

              when 'six monthly'
                clone_job.scheduled_date = clone_job.scheduled_date.to_date + 6.month
                clone_job.completed_date = clone_job.completed_date.to_date + 6.month if clone_job.completed_date.try(:to_date)

              when 'yearly'
                clone_job.scheduled_date = clone_job.scheduled_date.to_date + 1.year
                clone_job.completed_date = clone_job.completed_date.to_date + 1.year if clone_job.completed_date.try(:to_date)
            end
            clone_job.scheduled_date = clone_job.scheduled_date.to_date.strftime("%B %d %Y")
            clone_job.completed_date = clone_job.completed_date.to_date.strftime("%B %d %Y") if clone_job.completed_date.try(:to_date)
            clone_job.save
          end
        end

        format.html { redirect_to app_jobs_path, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to app_jobs_path, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to app_jobs_path, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:invoice_number, :user_id, :customer_id, :customer, :user, :title, :description, :scheduled_date, :completed_date, :status,
        :attachment)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def options_for_jobs(jobs)
    options = []

    jobs.each do |job|
      options << [
        "#{job.id} | #{job.scheduled_date} | #{job.customer&.business_name}",
        job.id
      ]
    end

    options
  end
end

app/views/app/jobs/_form.html.erb
<%= simple_form_for [:app, @job] do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <div class="row">
      <div class="col-md-4">
        <%= f.association :customer, collection: Customer.order(:business_name).pluck(:business_name, :id), prompt: "Choose a customer" %>
      </div>
      <div class="col-md-4">
        <%= f.association :user, collection: options_for_users(User.order(:first_name)), prompt: "Choose a user"  %>
      </div>
      <div class="col-md-4">
        <%= f.input :status, collection: ['Allocated', 'Completed'] %>
      </div>
      <div class="col-md-4">
        <%= f.input :completed_date, as: :string, input_html: { class: 'datepicker' } %>
      </div>
      <div class="col-md-4">
        <%= f.input :scheduled_date, as: :string, input_html: { class: 'datepicker' } %>
      </div>
      <div class="col-md-4">
        <%= f.input :invoice_number %>
      </div>
      <div class="col-md-4">
        <%= f.input :attachment %>
      </div>
    </div>
    <%= f.input :title %>
    <%= f.input :description, :as => :text, :input_html => {:rows => 5} %>
  </div>

  <% if @job.new_record? %>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <label>Repeat</label>
        <select name="type" class="form-control" id="repeat-type">
          <option value="none" selected>None</option>
          <option value="weekly">Weekly</option>
          <option value="monthly">Monthly</option>
          <option value="quarterly">Quarterly</option>
          <option value="six monthly">Six monthly</option>
          <option value="yearly">Yearly</option>
        </select>
      </div>
    </div>
    <div class="col-sm-6 box-number-repeats" style="display: none;">
      <label>Number of repeats</label>
      <input type="number" name="repeats" class="form-control" value="1" min="1">
    </div>
  </div>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-outline-primary" %>
  </div>
  <br>
<% end %>

<% content_for :page_js do %>
  <script type="text/javascript">
    $("#repeat-type").change(function(event) {
      if($(this).val() == 'none') {
        $('.box-number-repeats').slideUp(0);
      }else {
        $('.box-number-repeats').slideDown(0);
      }
    });
  </script>
<% end %>

app/views/app/jobs/edit.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Editing Job</h3>
  </div>
  <div class="box-body">
    <%= render 'form', job: @job %>
  </div>
</div>

app/views/app/jobs/index.html.erb
<div class="box">
  <div class="box-header">
    <strong>Search form:</strong>
  </div>
  <div class="box-body">
    <div class="border-form margin-bottom">
      <%= search_form_for @query, url: app_jobs_path do |f| %>
      <div class="row">
        <div class="col-md-3">
          <div class="form-group">
            <%= f.search_field :customer_business_name_cont, class: 'form-control', placeholder: 'Customer' %>
          </div>
        </div>
        <div class="col-md-2">
          <div class="form-group">
            <%= f.search_field :customer_business_name_cont, class: 'form-control', placeholder: 'Region' %>
          </div>
        </div>
        <div class="col-md-2">
          <div class="form-group">
            <%= f.search_field :user, class: 'form-control', placeholder: 'User' %>
          </div>
        </div>
        <div class="col-md-2">
          <div class="form-group">
            <%= f.search_field :status_cont, class: 'form-control', placeholder: 'Status' %>
          </div>
        </div>
        <div class="col-md-1">
          <div class="form-group">
            <%= f.search_field :scheduled_date_gteq, class: 'form-control datepicker', placeholder: 'Start date' %>
          </div>
        </div>
        <div class="col-md-1">
          <div class="form-group">
            <%= f.search_field :scheduled_date_lt, class: 'form-control datepicker', placeholder: 'End date' %>
          </div>
        </div>
        <div class="col-md-1">
          <button type="submit" class="btn btn-default">Search</button>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>


<div class="box">
  <div class="box-header with-border">
  <h3 class="box-title">Jobs</h3>
    <div class="box-tools">
      <ul class="pull-right">
        <a href="<%= new_app_job_path %>" class="btn btn-block btn-default btn-sm">New job</a>
      </ul>
    </div>
  </div>
  <div class="box-body">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Scheduled date</th>
          <th>Region</th>
          <th>Status</th>
          <th>Customer</th>
          <th>User</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td><%= job.scheduled_date %></td>
            <td><%= job.customer&.region %></td>
            <td><%= job.status %></td>
            <td><%= job.customer&.business_name %></td>
            <td><%= job.user&.first_name %> <%= job.user&.last_name %></td>
            <td></td>
            <td>
              <a href="<%= new_app_job_report_path(customer_id: job.customer&.id, user_id: job.user&.id, job_id: job.id) %>">
                Job report
              </a>
            </td>
            <td>
              <%= link_to 'Show', app_job_path(job) %> | <%= link_to 'Edit', edit_app_job_path(job) %> | <%= link_to 'Destroy', app_job_path(job), method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/app/jobs/new.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">New Job</h3>
  </div>
  <div class="box-body">
    <%= render 'form', job: @job %>
  </div>
</div>

app/views/app/jobs/repeat.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Repeat job #<%= @job.id %></h3>
  </div>
  <div class="box-body">
    <%= simple_form_for :jobs, url: handle_repeat_app_job_path do |f| %>
      <div class="row">
        <div class="col-sm-6">
          <div class="form-group">
            <label>Repeat</label>
            <select name="type" class="form-control">
              <option value="weekly">Weekly</option>
              <option value="monthly">Monthly</option>
              <option value="yearly">Yearly</option>
            </select>
          </div>
        </div>
        <div class="col-sm-6">
          <label>Number of repeats</label>
          <input type="number" name="repeats" class="form-control" value="1">
        </div>
      </div>
      <div class="text-left">
        <button class="btn btn-success">
          Submit
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/app/jobs/show.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Job details:</h3>
    <div class="box-tools">
      <ul class="pull-right">
        <a href="<%= new_app_job_report_path(customer_id: @job.customer&.id, user_id: @job.user&.id, job_id: @job.id) %>" class="btn btn-success btn-xs">
          Job report
        </a>
      </ul>
    </div>
  </div>
  <div class="box-body">

    <p>
      <strong>Customer:</strong>
      <%= @job.customer.business_name %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @job.user&.first_name %> <%= @job.user&.last_name %>
    </p>

    <p>
      <strong>Scheduled date:</strong>
      <%= @job.scheduled_date %>
    </p>

    <p>
      <strong>Completed date:</strong>
      <%= @job.completed_date %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @job.status %>
    </p>

    <% if @job.attachment.exists? %>
    <p>
      <strong>Attachment:</strong>
      <a href="<%= @job.attachment.url %>" target="_blank">
        Download
      </a>
    </p>
    <% end %>

    <p>
      <strong>Invoice number:</strong>
      <%= @job.invoice_number %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= @job.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @job.description %>
    </p>
    <a href="<%= edit_app_job_path(@job) %>"> Edit job</a> <br>
    <a href="<%= new_app_job_report_path(customer_id: @job.customer&.id, user_id: @job.user&.id, job_id: @job.id) %>"> Create job report</a>
  </div>
</div>