config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  namespace :app do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    resources :job_reports do
      member do
        post :certificate
      end
    end
    resources :jobs do
      member do
        post :repeat
      end
    end
    resources :customers
    resources :users do
      collection do
        get :profile
      end
    end
  end

  namespace :admin do
    resources :users
  end
end

app/controllers/app/dashboards_controller.rb
class App::DashboardsController < App::BaseController
  def index
    @jobs_without_certificate = JobReport.joins(:job)
                                   .where("jobs.status = ?", Job::STATUS_COMPLETED)
                                   .where(sent_certificate_at: nil)
                                   .order(id: :desc)
                                   .limit(5)
                                    
    @job_without_invoice = Job.where(status: Job::STATUS_COMPLETED)
                              .where("invoice_number = ''")
                              .order(id: :desc).limit(5)
    @job_without_report = Job.includes(:job_reports)
                             .where(status: Job::STATUS_COMPLETED)
                             .where(job_reports: {id: nil})
                             .order(id: :desc)
                             .limit(5)
    @overdue_jobs = Job.where("status != ?", Job::STATUS_COMPLETED)
                       .where("scheduled_date <= ?", Date.current)
                       .order(scheduled_date: :desc)
                       .limit(5)
  end
end

app/views/app/dashboards/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Completed jobs without invoice number</h3>
      </div>
      <div class="box-body">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Customer</th>
              <th>User</th>
              <th>Date</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @job_without_invoice.each do |job| %>
              <tr>
                <td><a href="<%= app_job_path(job) %>">#<%= job.id %></a></td>
                <td><a href="<%= app_customer_path(job.customer) %>"><%= job.customer&.business_name %></a></td>
                <td>
                  <a href="#"><%= job.user&.full_name %></a>
                </td>
                <td><%= job.completed_date.try(:strftime, "%d %b, %Y") %></td>
                <td><a href="<%= edit_app_job_path(job) %>"><i class="fa fa-pencil"></i> Edit</a></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Completed jobs without certificate sent</h3>
      </div>
      <div class="box-body">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Customer</th>
              <th>User</th>
              <th>Date</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @jobs_without_certificate.each do |report| %>
              <tr>
                <td><a href="<%= app_job_path(report.job) %>">#<%= report.job.id %></a></td>
                <td><a href="<%= app_customer_path(report.job.customer) %>"><%= report.job.customer&.business_name %></a></td>
                <td>
                  <a href="#"><%= report.job.user&.full_name %></a>
                </td>
                <td><%= report.job.completed_date.try(:strftime, "%d %b, %Y") %></td>
                <td>
                  <a href="<%= certificate_app_job_report_path(report) %>" data-method="POST">
                    <i class="fa fa-inbox"></i> Certificate</a>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Completed jobs without job report</h3>
      </div>
      <div class="box-body">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Customer</th>
              <th>User</th>
              <th>Date</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @job_without_report.each do |job| %>
              <tr>
                <td><a href="<%= app_job_path(job) %>">#<%= job.id %></a></td>
                <td><a href="<%= app_customer_path(job.customer) %>"><%= job.customer&.business_name %></a></td>
                <td>
                  <a href="#"><%= job.user&.full_name %></a>
                </td>
                <td><%= job.completed_date.try(:strftime, "%d %b, %Y") %></td>
                <td>
                  <a href="<%= new_app_job_report_path(customer_id: job.customer&.id, user_id: job.user&.id, job_id: job.id) %>">
                    <i class="fa fa-bar-chart"></i> Report
                  </a>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Overdue jobs</h3>
      </div>
      <div class="box-body">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Customer</th>
              <th>User</th>
              <th>Scheduled Date</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @overdue_jobs.each do |job| %>
              <tr>
                <td><a href="<%= app_job_path(job) %>">#<%= job.id %></a></td>
                <td><a href="<%= app_customer_path(job.customer) %>"><%= job.customer&.business_name %></a></td>
                <td>
                  <a href="#"><%= job.user&.full_name %></a>
                </td>
                <td><%= job.scheduled_date.try(:strftime, "%d %b, %Y") %></td>
                <td><a href="<%= edit_app_job_path(job) %>"><i class="fa fa-pencil"></i> Edit</a></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>