config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  namespace :app do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    resources :job_reports do
      member do
        post :certificate
      end
    end
    resources :jobs do
      member do
        post :repeat
      end
    end
    resources :customers
    resources :users do
      collection do
        get :profile
      end
    end
  end

  namespace :admin do
    resources :users
  end
end

app/views/layouts/admin/_header.html.erb
<header class="main-header">
    <!-- Logo -->
    <a href="/" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">Bth</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">Breathalyser</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span><img class="user-image" src="<%= current_user.avatar %>" alt=""> <%= current_user.first_name %> <%= current_user.last_name %></span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-header">
                <p>
                  <%= current_user.email %>
                </p>
              </li>
              <li class="user-footer">
                <div class="pull-left">
                  <a class="btn btn-default btn-flat" href="<%= profile_app_users_path %>">Profile</a>
                </div>
                <div class="pull-right">
                  <a data-method="DELETE" href="<%= destroy_user_session_path %>" href="#" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

app/views/layouts/admin/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <img class="img-circle" src="<%= current_user.avatar %>"  alt="profile">
      </div>
      <div class="pull-left info">
        <p><%= current_user.first_name %> <%= current_user.last_name %></p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
  <hr>
    <ul class="sidebar-menu" data-widget="tree">
      <li>
        <a href="<%= app_dashboards_path %>">
          <i class="fa fa-laptop"></i> <span> Dashboard</span>
        </a>
      </li>
      <% if can?(:manage, User)%>
        <li>
          <a href="<%= admin_users_path %>">
            <i class="fa fa-users"></i><span> Users</span>
          </a>
        </li>
      <% end %>
      <li>
        <a href="<%= app_customers_path %>">
          <i class="fa fa-user"></i><span> Customers</span>
        </a>
      </li>
      <li>
        <a href="<%= app_jobs_path %>">
          <i class="fa fa-file"></i><span> Jobs</span>
        </a>
      </li>
      <li>
        <a href="<%= app_job_reports_path %>">
          <i class="fa fa-signal"></i><span> Job reports</span>
        </a>
      </li>
      <li>
        <a href="<%= profile_app_users_path %>">
          <i class="fa fa-cog"></i><span> Settings</span>
        </a>
      </li>
    </ul>
  </section>
</aside>