config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  namespace :app do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    resources :job_reports do
      member do
        post :certificate
      end
    end
    resources :jobs do
      member do
        post :repeat
      end
    end
    resources :customers
    resources :users do
      collection do
        get :profile
      end
    end
  end

  namespace :admin do
    resources :users
  end
end

app/models/job_report.rb
# == Schema Information
#
# Table name: job_reports
#
#  id                         :integer          not null, primary key
#  job                        :string
#  customer                   :string
#  user                       :string
#  serial_number              :string
#  service_date               :string
#  previous_date              :string
#  clean_air                  :string
#  manual_gas                 :string
#  gas_level                  :string
#  total_count                :string
#  download                   :string
#  raw_reading                :string
#  comment                    :string
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  job_id                     :integer
#  user_id                    :integer
#  customer_id                :integer
#  manual_gas_two             :string
#  manual_gas_final           :string
#  calibration_factor         :string
#  gas_replaced               :string
#  consumables_invoice_number :string
#  calibration_successful     :string
#  attachment_file_name       :string
#  attachment_content_type    :string
#  attachment_file_size       :integer
#  attachment_updated_at      :datetime
#  sent_certificate_at        :datetime
#

class JobReport < ApplicationRecord
  belongs_to :job
  belongs_to :user, optional: true
  belongs_to :customer, optional: true

  has_attached_file :attachment
  validates_attachment_content_type :attachment,
    content_type: [
      'application/pdf'
    ]
  validates_attachment_size :attachment, less_than: 10.megabytes
end

app/controllers/app/job_reports_controller.rb
class App::JobReportsController < ApplicationController
  layout 'admin'
  before_action :set_job_report, only: [:show, :edit, :update, :destroy, :certificate]

  # GET /job_reports
  # GET /job_reports.json
  def index
    @query = JobReport.ransack(params[:q])
    @job_reports = @query.result(scheduled_date: :desc)
                                     .page(params[:page])
  end

  # GET /job_reports/1
  # GET /job_reports/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render(
          pdf: "Certificate",
          file: 'pdfs/certificate',
          locals: {
            job_report: @job_report
          }
        )
      end
    end
  end

  # GET /job_reports/new
  def new
    @job_report = JobReport.new user_id: params[:user_id] || current_user.id,
                                job_id: params[:job_id],
                                customer_id: params[:customer_id]
  end

  # GET /job_reports/1/edit
  def edit
  end

  # POST /job_reports
  # POST /job_reports.json
  def create
    @job_report = JobReport.new(job_report_params)

    respond_to do |format|
      if @job_report.save
        format.html { redirect_to app_job_reports_path, notice: 'Job report was successfully created.' }
        format.json { render :show, status: :created, location: @job_report }
      else
        format.html { render :new }
        format.json { render json: @job_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_reports/1
  # PATCH/PUT /job_reports/1.json
  def update
    respond_to do |format|
      if @job_report.update(job_report_params)
        format.html { redirect_to app_job_reports_path, notice: 'Job report was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_report }
      else
        format.html { render :edit }
        format.json { render json: @job_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_reports/1
  # DELETE /job_reports/1.json
  def destroy
    @job_report.destroy
    respond_to do |format|
      format.html { redirect_to app_job_reports_path, notice: 'Job report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def certificate
    if JobReportMailer.send_certificate(@job_report).deliver_now!
      @job_report.update_attribute :sent_certificate_at, Time.now
    end

    redirect_to app_job_reports_path,
                notice: 'Certificate was successfully sent.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_report
      @job_report = JobReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_report_params
      params.require(:job_report).permit(:job_id, :user_id, :customer_id, :job, :customer, :user, :serial_number, :service_date, :previous_date, :clean_air, :manual_gas, :gas_level, :total_count, :download, :raw_reading, :comment, :manual_gas_two, :manual_gas_final, :calibration_factor, :gas_replaced, :consumables_invoice_number, :calibration_successful, :attachment)
    end
end

app/helpers/job_reports_helper.rb
module JobReportsHelper
end

app/views/app/job_reports/_form.html.erb
<%= simple_form_for([:app, @job_report]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <h5 class="subheading-form">Details:</h5>
    <div class="row">
      <div class="col-md-4">
        <%= f.association :customer, collection: Customer.order(:business_name).pluck(:business_name, :id), prompt: "Choose a job"   %>
      </div>
      <div class="col-md-4">
        <%= f.association :job, collection: options_for_jobs(Job.includes(:customer).order(:id)), prompt: "Choose a job"  %>
      </div>
      <div class="col-md-4">
        <%= f.association :user, collection: options_for_users(User.order(:first_name)), prompt: "Choose a job"   %>
      </div>
      <div class="col-md-4">
        <%= f.input :attachment %>
      </div>
    </div>
    <h5 class="subheading-form">Service report:</h5>
    <div class="row">
      <div class="col-md-4">
        <%= f.input :serial_number %>
      </div>
      <div class="col-md-4">
        <%= f.input :service_date, input_html: { class: 'datepicker' }  %>
      </div>
      <div class="col-md-4">
        <%= f.input :previous_date, input_html: { class: 'datepicker' }  %>
      </div>
      <div class="col-md-4">
        <%= f.input :clean_air %>
      </div>
      <div class="col-md-4">
        <%= f.input :manual_gas %>
      </div>
      <div class="col-md-4">
        <%= f.input :manual_gas_two %>
      </div>
      <div class="col-md-4">
        <%= f.input :manual_gas_final %>
      </div>
      <div class="col-md-4">
        <%= f.input :gas_level %>
      </div>
      <div class="col-md-4">
        <%= f.input :gas_replaced, collection: ['Yes', 'No']   %>
      </div>
      <div class="col-md-4">
        <%= f.input :total_count %>
      </div>
      <div class="col-md-4">
        <%= f.input :download %>
      </div>
      <div class="col-md-4">
        <%= f.input :raw_reading %>
      </div>
      <div class="col-md-4">
        <%= f.input :calibration_factor %>
      </div>
      <div class="col-md-4">
        <%= f.input :calibration_successful, collection: ['Yes', 'No']  %>
      </div>
      <div class="col-md-4">
        <%= f.input :consumables_invoice_number %>
      </div>
    </div>
    <%= f.input :comment, :as => :text, :input_html => {:rows => 5}  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-outline-primary" %>
  </div>
  <br>
<% end %>

app/views/app/job_reports/edit.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Editing Job Report</h3>
  </div>
  <div class="box-body">
    <%= render 'form', job_report: @job_report %>
  </div>
</div>

app/views/app/job_reports/index.html.erb
<div class="box">
  <div class="box-header">
    <strong>Search form:</strong>
  </div>
  <div class="box-body">
    <div class="border-form margin-bottom">
      <%= search_form_for @query, url: app_job_reports_path do |f| %>
      <div class="row">
        <div class="col-md-2">
          <div class="form-group">
            <%= f.search_field :customer_business_name_cont, class: 'form-control', placeholder: 'Customer' %>
          </div>
        </div>
        <div class="col-md-2">
          <div class="form-group">
            <%= f.search_field :serial_number_cont, class: 'form-control', placeholder: 'Serial number' %>
          </div>
        </div>
        <div class="col-md-2">
          <div class="form-group">
            <%= f.search_field :user, class: 'form-control', placeholder: 'User' %>
          </div>
        </div>
        <div class="col-md-2">
          <div class="form-group">
            <%= f.search_field :consumables_invoice_number_cont, class: 'form-control', placeholder: 'Consumables #' %>
          </div>
        </div>
        <div class="col-md-1">
          <div class="form-group">
            <%= f.search_field :service_date_gteq, class: 'form-control datepicker', placeholder: 'Start date' %>
          </div>
        </div>
        <div class="col-md-1">
          <div class="form-group">
            <%= f.search_field :service_date_lteq, class: 'form-control datepicker', placeholder: 'End date' %>
          </div>
        </div>
        <div class="col-md-1">
          <button type="submit" class="btn btn-default">Search</button>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>


<div class="box">
  <div class="box-header">
  <h3 class="box-title">Job Reports</h3>
    <div class="box-tools">
      <ul class="pull-right">
        <a href="<%= new_app_job_report_path %>" class="btn btn-block btn-default btn-sm">New job report</a>
      </ul>
    </div>
  </div>
  <div class="box-body">
    <table class="table table-bordered">
      <thead>
    <tr>
      <th>Service date</th>
      <th>Serial number</th>
      <th>Customer</th>
      <th>User</th>
      <th>Consumables</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @job_reports.each do |job_report| %>
      <tr>
        <td><%= job_report.service_date %></td>
        <td><%= job_report.serial_number %></td>
        <td><%= job_report.customer.business_name %></td>
        <td><%= job_report.user&.first_name %> <%= job_report.user&.last_name %></td>
        <td><%= job_report.consumables_invoice_number %></td>
        <td>
          <a href="<%= certificate_app_job_report_path(job_report) %>" data-method="POST">Certificate</a> |
          <%= link_to 'Show', app_job_report_path(job_report) %> |
          <%= link_to 'Edit', edit_app_job_report_path(job_report) %> |
          <%= link_to 'Destroy', app_job_report_path(job_report), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/app/job_reports/new.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">New Job Report</h3>
  </div>
  <div class="box-body">
    <%= render 'form', job_report: @job_report %>
  </div>
</div>

app/views/app/job_reports/show.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Job Report</h3>
    <div class="box-tools">
      <a href="<%= app_job_report_path(format: :pdf) %>" class="btn btn-success btn-xs" target="_blank">
        <i class="fa fa-print"></i> Print
      </a>
      <a href="<%= certificate_app_job_report_path(@job_report) %>" data-method="POST" class="btn btn-success btn-xs">
        <i class="fa fa-send"></i> Send Certificate
      </a>
    </div>
  </div>

  <div class="box-body">
    <p>
      <strong>Job ID:</strong>
      <%= @job_report.job.id %>
    </p>

    <p>
      <strong>Customer:</strong>
      <%= @job_report.customer.business_name %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @job_report.user&.first_name %> <%= @job_report.user&.last_name %>
    </p>
    <br>
    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Serial number:</strong>
          <%= @job_report.serial_number %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Service date:</strong>
          <%= @job_report.service_date %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Previous date:</strong>
          <%= @job_report.previous_date %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Clean air:</strong>
          <%= @job_report.clean_air %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Manual gas:</strong>
          <%= @job_report.manual_gas %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Manual gas 2:</strong>
          <%= @job_report.manual_gas_two %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Manual gas final:</strong>
          <%= @job_report.manual_gas_final %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Gas level:</strong>
          <%= @job_report.gas_level %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Gas replaced:</strong>
          <%= @job_report.gas_replaced %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Total count:</strong>
          <%= @job_report.total_count %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Download:</strong>
          <%= @job_report.download %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Raw reading:</strong>
          <%= @job_report.raw_reading %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Attachment:</strong>
          <% if @job_report.attachment.exists? %>
          <a href="<%= @job_report.attachment.url %>" target="_blank">
            Download
          </a>
          <% end %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Calibration factor:</strong>
          <%= @job_report.calibration_factor %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Consumables invoice number:</strong>
          <%= @job_report.consumables_invoice_number %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Calibration successful:</strong>
          <%= @job_report.calibration_successful %>
        </p>
      </div>
    </div>
    <p>
      <strong>Comment:</strong>
      <%= @job_report.comment %>
    </p>

  </div>
</div>